source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

plugin 'cocoapods-keys', {
  :project => "iFW",
  :keys => [
    "iFWOneSignalKey"
  ]}

pod 'Alamofire', '~> 3.0'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
pod 'RealmSwift'
pod 'OneSignal'
